### ISSUE TITLE
Default indexURL is wrong in node?

### ISSUE THREAD

**Issue by hoodmane** [pyodide/pyodide#4232]
## 🐛 Bug

Install Pyodide into node and do:
```js
const {loadPyodide} = await import("pyodide/pyodide.mjs")
const py = await loadPyodide();
```
raises:

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/path/to/current/folder/file:/path/to/current/folder/node_modules/pyodide/pyodide.asm.js'

**Comment by rth** [comment]
Yes, I think we broke something, likely in https://github.com/pyodide/pyodide/pull/3967. We might need to re-think again what's a reasonable behavior there in node vs browser.

Also possibly same issue in https://github.com/pyodide/pyodide/issues/4174
