### ISSUE TITLE
Compilation error with out-of-tree builds with 0.24.0a1: LONG_BIT definition appears wrong for platform

### ISSUE THREAD

**Issue by lesteve** [pyodide/pyodide#4118]
## 🐛 Bug

Trying to use out-of-tree builds with 0.24.0a1 yields a compilation error: LONG_BIT definition appears wrong for platform

Maybe this is not supposed to work with the alpha version but will work fine with the 0.24 release?

I have found this same error in other places in the issue tracker e.g. https://github.com/pyodide/pyodide/discussions/2186#discussioncomment-2784855 or https://github.com/pyodide/pyodide/issues/775#issuecomment-717527769 but without a clear solution.

<details>
<summary>Excerpt of the build log with the error</summary>

```
building 'sklearn.__check_build._check_build' extension
creating build/temp.emscripten_3_1_44_wasm32-cpython-311/sklearn/__check_build
/tmp/tmp_co55dq1/cc -DNDEBUG -g -fwrapv -O3 -Wall -O2 -g0 -fPIC -DPY_CALL_TRAMPOLINE -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/tmp/build-env-o9s9adj9/include -I/opt/conda/envs/env/include/python3.11 -c sklearn/__check_build/_check_build.c -o build/temp.emscripten_3_1_44_wasm32-cpython-311/sklearn/__check_build/_check_build.o -g0 -O2
In file included from sklearn/__check_build/_check_build.c:35:
In file included from /opt/conda/envs/env/include/python3.11/Python.h:38:
/opt/conda/envs/env/include/python3.11/pyport.h:601:2: error: "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  601 | #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
      |  ^
sklearn/__check_build/_check_build.c:415:39: error: expression is not an integer constant expression
  415 |     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sklearn/__check_build/_check_build.c:415:41: note: division by zero
  415 |     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
      |                                         ^
2 errors generated.
emcc: error: '/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN -Werror=implicit-function-declaration --sysroot=/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -DNDEBUG -g3 -fwrapv -O3 -Wall -O2 -g0 -fPIC -DPY_CALL_TRAMPOLINE -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/tmp/build-env-o9s9adj9/include -I/opt/conda/envs/env/include/python3.11 -c -g0 -O2 -Werror=implicit-function-declaration -Werror=mismatched-parameter-types -Werror=return-type -O2 -g0 -fPIC -I/.pyodide-xbuildenv/xbuildenv/pyodide-root/cpython/installs/python-3.11.3/include/python3.11 -I/.pyodide-xbuildenv/xbuildenv/pyodide-root/cpython/installs/python-3.11.3/include/python3.11 sklearn/__check_build/_check_build.c -o build/temp.emscripten_3_1_44_wasm32-cpython-311/sklearn/__check_build/_check_build.o' failed (returned 1)
error: command '/tmp/tmp_co55dq1/cc' failed with exit code 1
```

</summary>
</details>

### To Reproduce

```sh
# Need set up emscripten 3.1.44 the usual way before
pip install pyodide-build==0.24.0a1
pyodide build scikit-learn
```

### Expected behavior

Builds a Pyodide wheel for scikit-learn

### Environment

- Pyodide Version: 0.24.0a1
- Browser version:
- Any other relevant information:

### Additional context

With Pyodide 0.24 the scikit-learn test suite fully passes, except some tests due to Pyodide limitations.

I saw the 0.24 release was approaching and I wanted to give a go to start running the scikit-learn tests inside Pyodide and in the scikit-learn CI.

**Comment by ryanking13** [comment]
Thanks for the report @lesteve! It looks like a regression. The same error doesn't occur in 0.23.4?

**Comment by lesteve** [comment]
This works fine with 0.23.4 indeed.

Note this is not specific to scikit-learn, for example you get the same error with simplejson or msgpack (except that both of these packages have a fall-back to a pure Python implementation which makes the wheel building succeed).

**Comment by ryanking13** [comment]
That's very interesting. I think Pyodide side didn't changed very much, so maybe there was a regression in between Emscripten 3.1.32 (Pyodide 0.23.4) and 3.1.44 (Pyodide 0.24.0a1).

I tried to reproduce the error with Pyodide 0.24.0a1 and scikit-learn 1.3.0 but failed (it build successfully).

**Comment by ryanking13** [comment]
I was also able to build scikit-build main branch with Pyodide 0.24.0a1. So probably this is not an issue in Emscripten.

Build log: [out.log](https://github.com/pyodide/pyodide/files/12550211/out.log)

**Comment by lesteve** [comment]
Hmmm indeed I tried in a Debian-based Docker container and it works fine. It doesn't work on my machine which is an ArchLinux-variant. Maybe I should consider myself lucky that it worked until Pyodide 0.23.

This is a little bit annoying but at the same time I can fully understand there are higher priorities for Pyodide ... I'll leave this issue open just in case someone has some insights and I'll close if not.

```
❯ cat /etc/os-release       
NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2023.03.26"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"
```

**Comment by lesteve** [comment]
I looked a bit more, for some reason this happens only in a conda environment. I can build fine on my ArchLinux machine in a Python virtual env (`python -m venv my-venv`) and I reproduce the issue using the `condaforge/miniforge3` Docker image based on Ubuntu 20.04.

**Comment by lesteve** [comment]
I can reproduce the issue in a CI see [scikit-learn PR](https://github.com/scikit-learn/scikit-learn/pull/27346) and [CI build](https://dev.azure.com/scikit-learn/scikit-learn/_build/results?buildId=58949&view=logs&jobId=6fac3219-cc32-5595-eb73-7f086a643b12&j=6fac3219-cc32-5595-eb73-7f086a643b12&t=6856d197-9931-5ad8-f897-5714e4bdfa31).

My hunch is that you get this problem as soon as you are not using your system Python (which is the case for the above CI on Azure or conda environment). I suspect there are things in `pywasmcross.py` like https://github.com/pyodide/pyodide/blob/3b428ceb6b7b9b3abfeab7a75fbf0fac6c9d76bb/pyodide-build/pyodide_build/pywasmcross.py#L234-L236 that removes the system Python includes which make it work in this case.
 
If you look at the failing command, you will see first the host Python (`-I/opt/conda/envs/env/include/python3.11`) and then xbuildenv one (`-I/.pyodide-xbuildenv/xbuildenv/pyodide-root/cpython/installs/python-3.11.3/include/python3.11`). This seems in the wrong order since you want first the xbuildenv one unless I am missing something. With some quick and dirty print statement, it seems like the include order is the one I am expecting in Pyodide 0.23.3.

Here is the command with a new line on each `-I`:
```
emcc: error: '/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN -Werror=implicit-function-declaration --sysroot=/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -DNDEBUG -g3 -fwrapv -O3 -Wall -O2 -g0 -fPIC -DPY_CALL_TRAMPOLINE -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
-I/tmp/build-env-o9s9adj9/include
-I/opt/conda/envs/env/include/python3.11 -c -g0 -O2 -Werror=implicit-function-declaration -Werror=mismatched-parameter-types -Werror=return-type -O2 -g0 -fPIC
-I/.pyodide-xbuildenv/xbuildenv/pyodide-root/cpython/installs/python-3.11.3/include/python3.11
-I/.pyodide-xbuildenv/xbuildenv/pyodide-root/cpython/installs/python-3.11.3/include/python3.11 sklearn/__check_build/_check_build.c -o build/temp.emscripten_3_1_44_wasm32-cpython-311/sklearn/__check_build/_check_build.o' failed (returned 1)
```

**Comment by ryanking13** [comment]
Thanks for the investigation @lesteve! Indeed I changed the order of arguments in #3866.

Probably we should update this part to filter out other local Python include directories as well.

https://github.com/pyodide/pyodide/blob/3b428ceb6b7b9b3abfeab7a75fbf0fac6c9d76bb/pyodide-build/pyodide_build/pywasmcross.py#L234-L236
