### PR TITLE
Update documentation for passing in global namespace

### LINKED ISSUE #2321: The instructions in the docs on executing code in a custom namespace (no longer?) seem to work
## 🐛 Bug

The instructions in the docs on executing code in a custom namespace (no longer?) seem to work with pyodide 0.19.1

### To Reproduce

```js
let my_namespace = pyodide.globals.dict();
pyodide.runPython(`x = 1 + 1`, my_namespace);
pyodide.runPython(`y = x ** x`, my_namespace);
my_namespace.y; // ==> 4
```

### Expected behavior

As defined in comments

### Actual

Get an exception: `Uncaught (in promise) TypeError: pyodide.globals.dict is not a function`

### PR DESCRIPTION
**Pull request by wlach**
* Fix API call so it actually works
* Update calling convention for changes in #2300
* Provide another example of creating a namespace from an existing set
  of JavaScript variables.

This closes #2321.

### CODE REVIEW

File: docs/usage/faq.md [hunk 1]
```diff
@@ -82,14 +82,29 @@ and returns a list of packages imported.
...
-The second argument to {any}`pyodide.eval_code` is a global namespace to execute the code in.
+The second argument to {any}`pyodide.eval_code` is an object
+which may include a `globals` element which creates a namespace for code to read from and write to.
 The namespace is a Python dictionary.
 
 ```javascript
-let my_namespace = pyodide.globals.dict();
-pyodide.runPython(`x = 1 + 1`, my_namespace);
-pyodide.runPython(`y = x ** x`, my_namespace);
-my_namespace.y; // ==> 4
```
Comment (wlach) [inline docs/usage/faq.md:92]: Noticed that this was also incorrect

**Comment by hoodmane** [comment]
Thanks @wlach!
