### PR TITLE
Fix replacing local include paths

### LINKED ISSUE #4118: Compilation error with out-of-tree builds with 0.24.0a1: LONG_BIT definition appears wrong for platform
## 🐛 Bug

Trying to use out-of-tree builds with 0.24.0a1 yields a compilation error: LONG_BIT definition appears wrong for platform

Maybe this is not supposed to work with the alpha version but will work fine with the 0.24 release?

I have found this same error in other places in the issue tracker e.g. https://github.com/pyodide/pyodide/discussions/2186#discussioncomment-2784855 or https://github.com/pyodide/pyodide/issues/775#issuecomment-717527769 but without a clear solution.

<details>
<summary>Excerpt of the build log with the error</summary>

```
building 'sklearn.__check_build._check_build' extension
creating build/temp.emscripten_3_1_44_wasm32-cpython-311/sklearn/__check_build
/tmp/tmp_co55dq1/cc -DNDEBUG -g -fwrapv -O3 -Wall -O2 -g0 -fPIC -DPY_CALL_TRAMPOLINE -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/tmp/build-env-o9s9adj9/include -I/opt/conda/envs/env/include/python3.11 -c sklearn/__check_build/_check_build.c -o build/temp.emscripten_3_1_44_wasm32-cpython-311/sklearn/__check_build/_check_build.o -g0 -O2
In file included from sklearn/__check_build/_check_build.c:35:
In file included from /opt/conda/envs/env/include/python3.11/Python.h:38:
/opt/conda/envs/env/include/python3.11/pyport.h:601:2: error: "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  601 | #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
      |  ^
sklearn/__check_build/_check_build.c:415:39: error: expression is not an integer constant expression
  415 |     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sklearn/__check_build/_check_build.c:415:41: note: division by zero
  415 |     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
      |                                         ^
2 errors generated.
emcc: error: '/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN -Werror=implicit-function-declaration --sysroot=/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -DNDEBUG -g3 -fwrapv -O3 -Wall -O2 -g0 -fPIC -DPY_CALL_TRAMPOLINE -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/tmp/build-env-o9s9adj9/include -I/opt/conda/envs/env/include/python3.11 -c -g0 -O2 -Werror=implicit-function-declaration -Werror=mismatched-parameter-types -Werror=return-type -O2 -g0 -fPIC -I/.pyodide-xbuildenv/xbuildenv/pyodide-root/cpython/installs/python-3.11.3/include/python3.11 -I/.pyodide-xbuildenv/xbuildenv/pyodide-root/cpython/installs/python-3.11.3/include/python3.11 sklearn/__check_build/_check_build.c -o build/temp.emscripten_3_1_44_wasm32-cpython-311/sklearn/__check_build/_check_build.o' failed (returned 1)
error: command '/tmp/tmp_co55dq1/cc' failed with exit code 1
```

</summary>
</details>

### To Reproduce

```sh
# Need set up emscripten 3.1.44 the usual way before
pip install pyodide-build==0.24.0a1
pyodide build scikit-learn
```

### Expected behavior

Builds a Pyodide wheel for scikit-learn

### Environment

- Pyodide Version: 0.24.0a1
- Browser version:
- Any other relevant information:

### Additional context

With Pyodide 0.24 the scikit-learn test suite fully passes, except some tests due to Pyodide limitations.

I saw the 0.24 release was approaching and I wanted to give a go to start running the scikit-learn tests inside Pyodide and in the scikit-learn CI.

### PR DESCRIPTION
**Pull request by ryanking13**
### Description

Resolve #4118 

When running `pyodide build` in conda env,

- `sys.prefix` is set to pypa/build virtualenv (`/tmp/...`)
- `sys.base_prefix` is set to conda directory (`/opt/conda/...`)

We need to replace the include path of both cases with our target install directory.

I locally checked with `simplejson` package that the error happened in #4118 is resolved with this fix.

cc: @lesteve 

### Checklists

- [x] Add a [CHANGELOG](https://github.com/pyodide/pyodide/blob/main/docs/project/changelog.md) entry
- [x] Add / update tests

### CODE REVIEW

File: pyodide-build/pyodide_build/pywasmcross.py [hunk 1]
```diff
@@ -226,14 +226,19 @@ def replay_genargs_handle_dashI(arg: str, target_install_dir: str) -> str | None
         The new argument, or None to delete the argument.
     """
     assert arg.startswith("-I")
-    if (
-        str(Path(arg[2:]).resolve()).startswith(sys.prefix + "/include/python")
-        and "site-packages" not in arg
```
Comment (lesteve) [inline pyodide-build/pyodide_build/pywasmcross.py:231]: You removed the `site-packages` case (where there was no replacement before this PR), I am not sure whether this was useful or not ...

File: pyodide-build/pyodide_build/pywasmcross.py [hunk 2]
```diff
@@ -226,14 +226,19 @@ def replay_genargs_handle_dashI(arg: str, target_install_dir: str) -> str | None
...
-    ):
-        return arg.replace("-I" + sys.prefix, "-I" + target_install_dir)
+
     # Don't include any system directories
     if arg[2:].startswith("/usr"):
```
Comment (lesteve) [inline pyodide-build/pyodide_build/pywasmcross.py:231]: Just curious, could this system directories case can be removed since it is already tackled by the `sys.base_prefix`?

Maybe there are other reasons to remove system directories than the Python include though.

**Review by lesteve — COMMENTED** [review]
Mostly out of curiosity, I have a few questions

File: pyodide-build/pyodide_build/pywasmcross.py [hunk 3]
```diff
@@ -226,14 +226,19 @@ def replay_genargs_handle_dashI(arg: str, target_install_dir: str) -> str | None
...
         return None
+
+    # Replace local Python include paths with the cross compiled ones
+    include_path = str(Path(arg[2:]).resolve())
+    if include_path.startswith(sys.prefix + "/include/python"):
+        return arg.replace("-I" + sys.prefix, "-I" + target_install_dir)
+
+    if include_path.startswith(sys.base_prefix + "/include/python"):
+        return arg.replace("-I" + sys.base_prefix, "-I" + target_install_dir)
```
Comment (lesteve) [inline pyodide-build/pyodide_build/pywasmcross.py:240]: And another question while I am at it. In my case (and it seems in out-of-tree builds in general), `target_install_dir` is `''`, so
`'-I/home/lesteve/micromamba/envs/pyodide-0.24.0a1/include/python3.11'`
gets replaced by
`'-I/include/python3.11'`

`/include/python3.11` does not exist on my machine and in general I would not expect it to exist so I am not too sure about the goal of the replacement besides disabling the include directory ... I guess maybe this replacement is useful for in-tree builds where target_install_dir is not `''`?

File: pyodide-build/pyodide_build/tests/test_pywasmcross.py [hunk 4]
```diff
@@ -145,6 +147,18 @@ def test_handle_command_ldflags(build_args):
     )
 
 
+@pytest.mark.parametrize(
+    "arg, expected",
+    [
+        ("-I/usr/include", None),
+        (f"-I{sys.prefix}/include/python3.11", "-I/target/include/python3.11"),
```
Comment (hoodmane) [inline pyodide-build/pyodide_build/tests/test_pywasmcross.py:154]: Could we money patch base_prefix and prefix for the test? Or do you think that's overkill?

File: pyodide-build/pyodide_build/pywasmcross.py (hunk 1 above)
Comment (ryanking13) [reply pyodide-build/pyodide_build/pywasmcross.py:231]: I think that part is not useful, as `site-packages` directory is in `/lib/site-packages` and not in `/include/python3.11/...`.

For header files in site-packages directories, we cover them by copying header files (e.g. numpy header files) into the virtual env directory:

https://github.com/pyodide/pyodide/blob/e492392f1b7716484a4681b707468fd191818d11/pyodide-build/pyodide_build/buildpkg.py#L534-L537

File: pyodide-build/pyodide_build/pywasmcross.py (hunk 2 above)
Comment (ryanking13) [reply pyodide-build/pyodide_build/pywasmcross.py:231]: I am not sure to be honest, we will have to check. Some codes in `pywasmcross.py` are very old so no one remembers the context 😅

File: pyodide-build/pyodide_build/pywasmcross.py (hunk 3 above)
Comment (ryanking13) [reply pyodide-build/pyodide_build/pywasmcross.py:240]: Oh, indeed we are setting it to an empty string in out-of-tree build.

https://github.com/pyodide/pyodide/blob/e492392f1b7716484a4681b707468fd191818d11/pyodide-build/pyodide_build/out_of_tree/build.py#L27

@hoodmane is it intended? I think it is incorrect.

File: pyodide-build/pyodide_build/tests/test_pywasmcross.py (hunk 4 above)
Comment (ryanking13) [reply pyodide-build/pyodide_build/tests/test_pywasmcross.py:154]: I think it is a good idea. I'll add update a test

File: pyodide-build/pyodide_build/pywasmcross.py (hunk 1 above)
Comment (lesteve) [reply pyodide-build/pyodide_build/pywasmcross.py:231]: OK makes sense, thanks!

File: pyodide-build/pyodide_build/pywasmcross.py (hunk 3 above)
Comment (hoodmane) [reply pyodide-build/pyodide_build/pywasmcross.py:240]: I think I just didn't know what this variable does or how to fill it, and setting it empty didn't break anything so I left it like that. Since something is breaking now it you probably know what should actually go there.

Comment (ryanking13) [reply pyodide-build/pyodide_build/pywasmcross.py:240]: Okay, I'll update that part to set the correct target_install_dir. I think it didn't break since we append [cpython include](https://github.com/pyodide/pyodide/blob/e492392f1b7716484a4681b707468fd191818d11/Makefile.envs#L159) all the time.

**Comment by ryanking13** [comment]
@hoodmane @rth Could you review this when you have time?

**Review by rth — APPROVED** [review]
Thanks for fixing it @ryanking13 and @lesteve for investigating! LGTM.

**Comment by lesteve** [comment]
Great thanks for the fix! In a ideal world, this would be included in 0.24.1, when it makes sense for you to release 0.24.1.

**Comment by rth** [comment]
Yes, we'll backport it.
