### ISSUE TITLE
The instructions in the docs on executing code in a custom namespace (no longer?) seem to work

### ISSUE THREAD

**Issue by wlach** [pyodide/pyodide#2321]
## 🐛 Bug

The instructions in the docs on executing code in a custom namespace (no longer?) seem to work with pyodide 0.19.1

### To Reproduce

```js
let my_namespace = pyodide.globals.dict();
pyodide.runPython(`x = 1 + 1`, my_namespace);
pyodide.runPython(`y = x ** x`, my_namespace);
my_namespace.y; // ==> 4
```

### Expected behavior

As defined in comments

### Actual

Get an exception: `Uncaught (in promise) TypeError: pyodide.globals.dict is not a function`

**Comment by hoodmane** [comment]
Thanks @wlach! We need to replace `pyodide.globals.dict` ==> `pyodide.globals.get("dict")`:
```js
let my_namespace = pyodide.globals.get("dict")(); // changed here
pyodide.runPython(`x = 1 + 1`, my_namespace);
pyodide.runPython(`y = x ** x`, my_namespace);
my_namespace.y; // ==> 4
```

**Comment by wlach** [comment]
> Thanks @wlach! We need to replace `pyodide.globals.dict` ==> `pyodide.globals.get("dict")`:
> 
> ```js
> let my_namespace = pyodide.globals.get("dict")(); // changed here
> pyodide.runPython(`x = 1 + 1`, my_namespace);
> pyodide.runPython(`y = x ** x`, my_namespace);
> my_namespace.y; // ==> 4
> ```

Ah good! Let me know if you'd like me to file a PR. While we're here, I also have a followup question which might make a nice addition to the docs if you have an answer: https://github.com/pyodide/pyodide/discussions/2322

**Comment by hoodmane** [comment]
If you could make a PR updating the docs fixing this and adding an answer / example for #2322 that would be fantastic.
