### ISSUE TITLE
While loading micropip can't access property "node"

### ISSUE THREAD

**Issue by zerothi** [pyodide/pyodide#6004]
## 🐛 Bug

I really have little clue as to why this happens:
```
Pyodide has suffered a fatal error. Please report this to the Pyodide maintainers.
The cause of the error was: TypeError
can't access property "node", this is undefined
Stack trace:
getattr@http://127.0.0.1:8000/extensions/@jupyterlite/pyodide-kernel-extension/static/352.cc74f63a8f779ace30b6.js?v=cc74f63a8f779ace30b6:2:208752
stat@http://127.0.0.1:8000/static/pyodide/pyodide.asm.js:8:80895
___syscall_stat64@http://127.0.0.1:8000/static/pyodide/pyodide.asm.js:8:140779
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[8882]:0x4659f3
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[9510]:0x47f22c
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[6743]:0x3a5d25
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[6740]:0x3a539d
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[3533]:0x262855
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[3534]:0x26e454
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[1138]:0x168d34
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[1150]:0x169a49
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[1149]:0x169807
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[4057]:0x2a9d77
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[3533]:0x265f46
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[3802]:0x292711
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[1849]:0x1938eb
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[3533]:0x265f1d
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[3534]:0x26e454
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[1138]:0x168d34
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[1134]:0x168a99
@http://127.0.0.1:8000/static/pyodide/pyodide.asm.wasm:wasm-function[451]:0x118c97
pe@http://127.0.0.1:8000/static/pyodide/pyodide.asm.js:8:632818
callKwargs@http://127.0.0.1:8000/static/pyodide/pyodide.asm.js:8:651089
install@http://127.0.0.1:8000/static/pyodide/pyodide.asm.js:8:660481
installPackage@http://127.0.0.1:8000/static/pyodide/pyodide.asm.js:8:666522
downloadAndInstall@http://127.0.0.1:8000/static/pyodide/pyodide.asm.js:8:666873

12:41:50 PM The following error occurred while loading micropip:
12:41:50 PM can't access property "node", this is undefined
12:41:50 PM this[#t].importlib.invalidate_caches is not a function
```

So it, seems like something related to node.js, but I am not sure, at all!

### Environment

- Pyodide Version: released 0.29.0 (works with 0.27.3)
- Browser version: Firefox 140.5.0esr (64-bit) (debian)
- Any other relevant information:

I am using a simple build script, looks like this:
```bash
#!/bin/bash

# Global variables for the directories:
#  jl_dir is the directory for the jupyter-lite installation
#  venv_dir is the directory for the virtual env for creating it.
jl_dir=jupyter-lite
pyodide_version=0.29.0
pyodide_version=0.27.3
venv_dir=venv-jl

# These packages will be installed in the virtual environment
# These packages are *not* what will be in the final jupyter-lite
# installation, but rather these packages are necessary for
# 
# They are necessary for building pyodide
packages=(
  jupyterlite-core
  jupyterlite-pyodide-kernel
  jupyter_server
  jupyterlab-tour
  jupyterlab-night
  jupyterlab_server
  notebook # enables switching between notebook and lab workflow
  libarchive-c
)

if [ ! -d $venv_dir ]; then
  python3 -m venv $venv_dir
  source $venv_dir/bin/activate
  pip install "${packages[@]}"
  deactivate
fi

# Ok, so now we have a venv
source $venv_dir/bin/activate


# Now try and build/host things
# Because we are rebuilding, we should delete the database as well
# (it if exists!)
rm -rf .cache .jupyterlite.doit.db
rm -rf $jl_dir

# List files in the current directory.
ls -la

# Collect the arguments for the pyodide installation.
common_args=(
  # The configuration should be the jupyter_lite_config.json
  # equivalently we can just pass it at init time:
  --config build-config.json
  --contents contents
  --output-dir $jl_dir
  --lite-dir .
)

# We have the configuration file in jupyter-lite.json
# Now, we should build the infrastructure
echo ">>> initialization..."
#jupyter lite init "${common_args[@]}" || exit 1
echo ">>> building..."
jupyter lite build --pyodide ./pyodide-${pyodide_version}.tar.bz2 "${common_args[@]}" || exit 1
```

### Additional context

I am using exactly the same installation script but only changing the `pyodide` version.

So when I change between
```
pyodide_version=0.29.0
pyodide_version=0.27.3
```
I can get it working with 0.27.3, but it creates the above error when using 0.29.0?

I tried searching for the `node` error, but couldn't find anything else.

Sorry to post this here, it seems like it's a pyodide *problem*, but let me know if this should be moved to jupyterlite?

I am open to help in any way, but I am not sure where to dig/provide information...

**Comment by ryanking13** [comment]
Well, I believe this is jupyterlite issue as they heavily patch micropip. Could you open an issue there?

**Comment by zerothi** [comment]
Thanks, will do!
