### ISSUE TITLE
0.28.0: micropip lockFileURL failing when provided

### ISSUE THREAD

**Issue by WebReflection** [pyodide/pyodide#5736]
## 🐛 Bug

We've discussed this in Discord but I haven't seen any bug around it so here it is.

### To Reproduce

This page tries to store the `micropip.freeze()` result somewhere and reuse it for any other reload of the page.

As soon as that frozen cache is used as valid URL, an error about `TypeError: _emscripten_stack_get_current is not a function` is shown:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="module">
        // add ?clear to your test page to drop the entry
        if (location.search === '?clear') {
            localStorage.removeItem("test");
            location.href = location.href.slice(0, -6);
            throw new Error('reloading anyway');
        }

        import { loadPyodide } from "https://cdn.jsdelivr.net/pyodide/v0.28.0/full/pyodide.mjs";

        let timeout = 0;
        addEventListener('error', () => {
            clearTimeout(timeout);
            document.body.append('ERROR');
        });

        const json = localStorage.getItem("test");
        const options = {
            // not specific to the package, anyone fails
            packages: ["numpy"],
        };

        if (json) {
            options.lockFileURL = URL.createObjectURL(new Blob(
                [json],
                { type: 'application/json' },
            ));
        }

        const pyodide = await loadPyodide(options);

        if (json) {
            // irrelevant for the bug, just for correctness/example
            URL.revokeObjectURL(options.lockFileURL);
        }
        else {
            await pyodide.loadPackage('micropip');
            const micropip = pyodide.pyimport('micropip');
            await micropip.install(options.packages, { keep_going: true });
            const frozen = micropip.freeze();
            localStorage.setItem("test", frozen);
            micropip.destroy();
            // first time it's fine, next time refresh
            // and you'll see a weird error
        }

        timeout = setTimeout(() => {
            document.body.append('ALL GOOD - REFRESH');
        }, 1000);
    </script>
</head>
</html>
```

### Expected behavior

We use IndexedDB instead but the outcome is the same, what supposed to be a way to ensure faster bootstrap became "*harakiri*" because without any caching attempt things just work and things worked up to 0.28.0 release, but nothing in the BREAKING CHANGES suggests we're doing something really wrong and the error is a bit cryptic because it doesn't provide any follow-up action or detail about what's actually wrong in the process.

### Environment

- Pyodide Version: 0.28.0
- Browser version: latest
- Any other relevant information: @hoodmane knows about it and I think he started already some sort of investigation around it.

### Additional context

Pinging @ntoll if interested as this is making our project (*PyScript*) unable to adopt latest/greatest features of this lovely runtime.

Thanks for having a look 🙏

**Comment by hoodmane** [comment]
There are two different bugs here and one of them is an easy fix for a problem caused by https://github.com/pyodide/pyodide/pull/5621 I'll fix it on Monday.
The other may be a regression somewhere in our package loading system.

**Comment by ryanking13** [comment]
Thanks for the report. I'll check this error during the weekend.

I am not sure why `TypeError: _emscripten_stack_get_current is not a function` is happening though. This symbol obviously exists in the WASM module:

```
>>> typeof pyodide._module._emscripten_stack_get_current
'function'
```

Maybe that function is called before the WASM module is fully initialized for some unknown reason.

**Comment by ryanking13** [comment]
Okay, another half of the problem is that when `options.packages` is passed, it loads the packages before the WASM modules are fully loaded, so accessing native functions such as `_emscripten_stack_get_current ` is not available. For stdout, we were redirecting the messages to null, but not for stderr.

https://github.com/pyodide/pyodide/blob/646f9f30c5afd0f24805d6bcb1563b85a81c83e3/src/js/load-package.ts#L87

**Comment by alumni** [comment]
Looks like also for you, `loadPyodide({ lockFileContent })` would be more helpful than `loadPyodide({ lockFileURL })` :)

Maybe it would be a nice idea to have this in the API?

_Later edit_: the Blob workaround does not work for me on NodeJS: `ENOENT: no such file or directory, open 'blob:nodedata:65debf41-be76-480b-9a7e-8277f48785fb'`

**Comment by WebReflection** [comment]
@alumni we don't run on NodeJS ... we followed just instructions that have been working to date. We're stuck with 0.27 until this get merged and released with fixes but of course, if there's any better options we'll use it, although this won't play well if users explicitly use a previous version of Pyodide, in case that option wasn't available before.

**Comment by ryanking13** [comment]
> Looks like also for you, loadPyodide({ lockFileContent }) would be more helpful than loadPyodide({ lockFileURL }) :), Maybe it would be a nice idea to have this in the API?

Yes. I didn't expect people would use blob URLs to load lockfile, so we will need to find out what would be the best way to deal with different use cases.

**Comment by alumni** [comment]
Actually I didn't know how to use it, I thought `lockFileURL` can only be a URL, not a file path. So I tried to do it like that in NodeJS :)

I switched to `lockFileURL` in the meantime :)

**Comment by WebReflection** [comment]
> I didn't expect people would use blob URLs to load lockfile

happy to hear from client side only how else one would `micropip.freeze()` store that content and retrieve it next time to have a URL that `loadPyodide` can be happy about ... users can add, remove, or change packages all the time and the bootstrap does the rest but it's entirely client side, any hint/clue idea? would `lockFileContent` out of a *File* created via a *Blob* make any difference? If that's the case, we can surely have a look and see if it's any better or faster ... also worth mentioning we do bootstrap same way main thread or workers so if there's anything different in there too please let us know, thank you!

**Comment by alumni** [comment]
I actually had to look at the Pyodide source code in this repo to figure out how things are working (because the one in node_modules is unreadable). But I discovered that Pyodide relies mostly on the lockfile promise, which is created by fetching the URL.

Honestly, Pyodide could let the users provide the lockfile content directly, without having to add all this complexity for fetching from a URL or reading it from the file system. And it would make things easy for the users if they want a different lockfile each time.

**Comment by hoodmane** [comment]
Yeah I'm in favor of adding a `lockFilePromise` option to `loadPyodide` which should resolve to the lock file contents. Would be a simple enough change.

**Comment by WebReflection** [comment]
Would that be a `Promise.resolve(previousMicroPipFrozenContent)` value?

**Comment by ryanking13** [comment]
>Would that be a Promise.resolve(previousMicroPipFrozenContent) value?

Yes.

**Comment by WebReflection** [comment]
As pyodide provides its version AOT we might use that field when it’s 0.28.x so this works well for us too

**Comment by alumni** [comment]
Maybe the best thing would be:

```ts
type PromiseOrValue<T> = T | Promise<T>;

export interface LoadOptions = {
  lockFileURL?: string;
  lockFile?: PromiseOrValue<string | PyodideInterface['lockfile']>;
}
```

I tend towards the object format rather than the stringified object :) Less transformations needed if you have an object already and less things for Pyodide to handle.

**Comment by WebReflection** [comment]
`micropip.freeze()` returns a string though so either Pyodide or "*us*" need to convert that as JSON ... I think having that accept the produced output as input (hence json string) would produce the least amount of surprises

**Comment by ryanking13** [comment]
This is fixed in 0.28.1. We have another node.js related lockfile issue, so we will release 0.28.2 soon anyways, but closing as resolved.
