### PR TITLE
Fix RobotRaconteur package with Emscripten 3.1.66+

### PR DESCRIPTION
**Pull request by johnwason**
RobotRaconteur package failed to build with Emscripten 3.1.66 as discussed in #5382. This PR is an attempt to fix the problem.

### CODE REVIEW

**Comment by hoodmane** [comment]
Thanks for looking into it @johnwason

**Comment by johnwason** [comment]
@hoodmane I am getting this error when building pyodide locally:

```
libtool: compile:  /src/emsdk/emsdk/upstream/emscripten/emcc -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -Wall -O3 -fPIC -DWASM_BIGINT -fexceptions -c src/wasm32/ffi.c -o src/wasm32/ffi.o
src/wasm32/ffi.c:45:20: error: expected identifier
EM_JS_DEPS(libffi, "$getWasmTableEntry,$setWasmTableEntry,$getEmptyTableSlot,$convertJsFunctionToWasm");
                   ^
src/wasm32/ffi.c:45:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
EM_JS_DEPS(libffi, "$getWasmTableEntry,$setWasmTableEntry,$getEmptyTableSlot,$convertJsFunctionToWasm");
^
int
2 errors generated.
emcc: error: '/src/emsdk/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=13 -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/src/emsdk/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -Wall -O3 -fPIC -fexceptions -DHAVE_CONFIG_H -I. -I. -I./include -Iinclude -I./src -DWASM_BIGINT -c -fcolor-diagnostics src/wasm32/ffi.c -o src/wasm32/ffi.o' failed (returned 1)
make[3]: *** [Makefile:1341: src/wasm32/ffi.lo] Error 1
make[3]: Leaving directory '/src/cpython/build/libffi'
make[2]: *** [Makefile:1414: install-recursive] Error 1
make[2]: Leaving directory '/src/cpython/build/libffi'
make[1]: *** [Makefile:100: /src/cpython/installs/python-3.12.7/lib/libffi.a] Error 2
make[1]: Leaving directory '/src/cpython'
make: *** [Makefile:312: /src/cpython/installs/python-3.12.7/lib/python3.12] Error 2
```

**Comment by hoodmane** [comment]
That is weird. Something getting messed up with the headers somehow? I don't recall ever seeing that error before. @ryanking13 @agriyakhetarpal any ideas? I assume if you do `make -C emsdk clean; make -C cpython clean` and start over you get the same error?


Maybe you could build against our nighty cross build environment. @ryanking13 just added it so he'd have to tell us how it works and maybe make a new one based on the updated emscripten.

**Comment by johnwason** [comment]
Using `make -C emsdk clean; make -C cpython clean` fixed the build problem. I used git clean but I guess it didn't remove something important.

**Comment by johnwason** [comment]
@hoodmane this PR is passing now. I am not sure why the emcc compiler needed these extra `#include` statement. This code has been working for a long time.

**Comment by hoodmane** [comment]
Generally this sort of thing happens because there's a regression in clang tip of tree that emscripten pulls in. Presumably it will get fixed before it gets to clang stable so it only bothers us.
